export default `[
  {"id":1,
    "price":134.79,
    "category":"women",
    "imgUrl":"/assets/img/goods-w-1.jpg",
    "amount":1,
    "title":"WOMENS BURNT ORANGE CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 100% cotton."
  },
  {"id":2,
    "price":234.79,
    "category":"women",
    "imgUrl":"/assets/img/goods-w-2.jpg",
    "amount":7,
    "title":"WOMENS BURNT ORANGE CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 100% cotton."
   },
  {"id":3,
    "price":334.79,
    "category":"men",
    "imgUrl":"/assets/img/goods-m-1.jpg",
    "amount":3,
    "title":"MENS BURNT GRAY CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 100% cotton."
  },
  {"id":4,
    "price":434.79,
    "category":"women",
    "imgUrl":"/assets/img/goods-w-1.jpg",
    "amount":2,
    "title":"WOMENS BURNT RED CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 0% cotton."
  },
  {"id":5,
    "price":604.79,
    "category":"men",
    "imgUrl":"/assets/img/goods-m-1.jpg",
    "amount":3,
    "title":"MENS BURNT  CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 1090% cotton."
 },
  {"id":6,
    "price":834.79,
    "category":"women",
    "imgUrl":"/assets/img/goods-w-3.jpg",
    "amount":2,
    "title":"WOMENS BURNT PINK  TEE",
    "description": "Classic casual t-short for women on the move. 199% cotton."
  },
  {"id":7,
    "price":224.59,
    "category":"men",
    "imgUrl":"/assets/img/goods-m-1.jpg",
    "amount":1,
    "title":"WOMENS BURNT ORANGE CASUAL TEE",
    "description": "Classic casual t-short for men on the move. 1% cotton."
  },
  {"id":8,
    "price":134.79,
    "category":"women",
    "imgUrl":"/assets/img/goods-w-2.jpg",
    "amount":100,
    "title":"WOMENS BURNT ORANGE CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 100% cotton."
  },
  {"id":9,
    "price":1231,
    "category":"men",
    "imgUrl":"/assets/img/goods-m-1.jpg",
    "amount":2,
    "title":"MENS BURNT ORANGE CASUAL TEE",
    "description": "Classic casual t-short for women on the move. 100% cotton."
  }
]`